const SLUGS = [
    {title: 'chassing-ghost',
     why: 'Three.js learning',
     date: 2018,
     techno: 'Three.js'},
     {title: 'ima-made-nando-mo',
     why: 'Javascript animations learning',
     date: 2018,
     techno: 'Canvas - Javascript vanilla'},
     {title: 'rolling-star',
     why: 'Codevember 2019 - Day 1 : Contrast',
     date: 2019,
     techno: 'HTML Dom - CSS class'},
     {title:  'sweet-dreams',
     why: 'Codevember 2019 - Day 2 : Geometric',
     date: 2019,
     techno: 'Three.js'},
     {title: 'zar-se-godine-ne-broje',
     why: 'Codevember 2019 - Day 3 : Deep',
     date: 2019,
     techno: 'HTML Dom - CSS Animation'},
     {title: 'lost-one-no-goukoku',
     why: 'Codevember 2019 - Day 4 : Big',
     date: 2019,
     techno: 'Three.js'},
     {title: 'nakushita-kotoba',
     why: 'Codevember 2019 - Day 5 : Light',
     date: 2019,
     techno: 'Three.js'},
     {title: 'i-love-rock-n-roll',
     why: 'Codevember 2019 - Day 6 : Music',
     date: 2019,
     techno: 'Canvas - Javascript vanilla'},
     {title: 'ojos-de-cielo',
     why: 'Codevember 2019 - Day 7 : Shape',
     date: 2019,
     techno: 'Canvas - Javascript vanilla'},
     {title: 'stronger',
     why: 'Codevember 2019 - Day 8 : Data',
     date: 2019,
     techno: 'Three.js'},
     {title: 'the-game',
     why: 'Codevember 2019 - Day 9 : Game',
     date: 2019,
     techno: 'Canvas - Javascript vanilla'},
     {title: 'igra-rokenrol-cela-jugoslavija',
     why: 'Codevember 2019 - Day 10 : Old',
     date: 2019,
     techno: 'HTML Dom - Javascript vanilla'},
     {title: 'angel-night',
     why: 'Codevember 2019 - Day 11 : Perspective',
     date: 2019,
     techno: 'Three.js'},
     {title: 'canon-in-d',
     why: 'Codevember 2019 - Day 12 : Ice',
     date: 2019,
     techno: 'Three.js'},
     {title: 'nessun-grado-di-separazione',
     why: 'Codevember 2019 - Day 13 : Line',
     date: 2019,
     techno: 'Three.js - Canvas - Javascript vanilla'},
     {title: 'rasputin',
     why: 'Codevember 2019 - Day 14 : Bouncy',
     date: 2019,
     techno: 'Canvas - Javascript vanilla'}
] 